sudo: required
services:
    - docker

before_install:
    - docker build -t lucasrivelles/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true lucasrivelles/react-test npm test

after_success:
    - docker build -t lucasrivelles/multi-client ./client
    - docker build -t lucasrivelles/multi-nginx ./nginx
    - docker build -t lucasrivelles/multi-server ./server
    - docker build -t lucasrivelles/multi-worker ./worker
    # Login to the Docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push into Docker Hub
    - docker push lucasrivelles/multi-client
    - docker push lucasrivelles/multi-nginx
    - docker push lucasrivelles/multi-server
    - docker push lucasrivelles/multi-worker